const emailData = [
    // 📥 Inbox Emails
    {
      id: "1",
      from: "john.doe@example.com",
      to: "alice.smith@example.com",
      subject: "Meeting Reminder",
      date: "2024-01-28T10:30:00Z",
      content: "Hi Alice, just a reminder about our meeting tomorrow at 11 AM.",
      isRead: false,
      labels: ["Work"],
      attachments: [],
      type: "inbox",
    },
    {
      id: "2",
      from: "support@ecommerce.com",
      to: "alice.smith@example.com",
      subject: "Order Confirmation - #123456",
      date: "2024-01-27T14:20:00Z",
      content: "Thank you for your order! Your package will be shipped soon.",
      isRead: true,
      labels: ["Purchases"],
      attachments: ["invoice-123456.pdf"],
      type: "inbox",
    },
    {
      id: "3",
      from: "newsletter@techworld.com",
      to: "alice.smith@example.com",
      subject: "Top 5 Tech Trends of 2024",
      date: "2024-01-26T09:15:00Z",
      content: "Discover the latest innovations in AI, blockchain, and more.",
      isRead: true,
      labels: ["News"],
      attachments: [],
      type: "inbox",
    },
    {
      id: "4",
      from: "no-reply@socialmedia.com",
      to: "alice.smith@example.com",
      subject: "New Login Alert",
      date: "2024-01-25T18:20:00Z",
      content: "A new login was detected on your account from a new device.",
      isRead: false,
      labels: ["Security"],
      attachments: [],
      type: "inbox",
    },
    {
      id: "5",
      from: "marketing@company.com",
      to: "alice.smith@example.com",
      subject: "Exclusive Offer Inside!",
      date: "2024-01-24T12:30:00Z",
      content: "Get 20% off on your next purchase! Use code SAVE20 at checkout.",
      isRead: true,
      labels: ["Promotions"],
      attachments: ["discount-coupon.pdf"],
      type: "inbox",
    },
  
    // 📤 Sent Emails (Outbox)
    {
      id: "6",
      from: "alice.smith@example.com",
      to: "john.doe@example.com",
      subject: "Re: Meeting Reminder",
      date: "2024-01-28T11:00:00Z",
      content: "Thanks for the reminder, John! I'll be there on time.",
      isRead: true,
      labels: ["Work"],
      attachments: [],
      type: "sent",
    },
    {
      id: "7",
      from: "alice.smith@example.com",
      to: "customer.service@ecommerce.com",
      subject: "Issue with my Order #123456",
      date: "2024-01-27T16:05:00Z",
      content: "Hello, I received a wrong item in my order. Please assist.",
      isRead: true,
      labels: ["Purchases"],
      attachments: ["order-receipt.pdf"],
      type: "sent",
    },
    {
      id: "8",
      from: "alice.smith@example.com",
      to: "newsletter@techworld.com",
      subject: "Re: Top 5 Tech Trends",
      date: "2024-01-26T10:00:00Z",
      content: "Great insights! Do you have a detailed report on AI trends?",
      isRead: true,
      labels: ["News"],
      attachments: [],
      type: "sent",
    },
    {
      id: "9",
      from: "alice.smith@example.com",
      to: "it-support@company.com",
      subject: "Help: Password Reset Issue",
      date: "2024-01-25T19:45:00Z",
      content: "I'm unable to reset my password. Can you assist?",
      isRead: false,
      labels: ["Work", "Security"],
      attachments: [],
      type: "sent",
    },
    {
      id: "10",
      from: "alice.smith@example.com",
      to: "bob.jones@example.com",
      subject: "Follow-up: Project Proposal",
      date: "2024-01-24T13:15:00Z",
      content: "Hey Bob, did you get a chance to review the proposal?",
      isRead: true,
      labels: ["Work"],
      attachments: ["proposal.pdf"],
      type: "sent",
    },
  
    // ✏️ Draft Emails
    {
      id: "11",
      from: "alice.smith@example.com",
      to: "charlie.miller@example.com",
      subject: "Invitation to Tech Conference",
      date: "2024-01-28T08:10:00Z",
      content: "Hi Charlie, I wanted to invite you to the upcoming Tech Conference.",
      isRead: false,
      labels: ["Networking"],
      attachments: [],
      type: "draft",
    },
    {
      id: "12",
      from: "alice.smith@example.com",
      to: "hr@company.com",
      subject: "Job Application for Frontend Developer",
      date: "2024-01-27T17:20:00Z",
      content: "Dear HR, I am interested in the Frontend Developer position...",
      isRead: false,
      labels: ["Career"],
      attachments: ["resume.pdf"],
      type: "draft",
    },
    {
      id: "13",
      from: "alice.smith@example.com",
      to: "support@bank.com",
      subject: "Query: Credit Card Charges",
      date: "2024-01-26T09:50:00Z",
      content: "Hello, I noticed an unexpected charge on my credit card...",
      isRead: false,
      labels: ["Finance"],
      attachments: [],
      type: "draft",
    },
    {
      id: "14",
      from: "alice.smith@example.com",
      to: "mentor@example.com",
      subject: "Request for Guidance",
      date: "2024-01-25T20:30:00Z",
      content: "Hey, I would love to get your advice on my career in web dev...",
      isRead: false,
      labels: ["Career"],
      attachments: [],
      type: "draft",
    },
    {
      id: "15",
      from: "alice.smith@example.com",
      to: "event@conference.com",
      subject: "Speaking Opportunity Inquiry",
      date: "2024-01-24T14:00:00Z",
      content: "Hi, I'm interested in speaking at your conference. Can we discuss?",
      isRead: false,
      labels: ["Networking"],
      attachments: [],
      type: "draft",
    },
  ];

 export const inboxMail = emailData.filter((s)=>s.type === "inbox")
 export const outboxMail = emailData.filter((s)=>s.type === "sent")
 export const draftMail = emailData.filter((s)=>s.type === "draft")
  
  export default emailData;
  